services:
  web_api:
    container_name: crm_api
    build: ./CRMSystemAPI
    ports:
      - "5000:8080"
    depends_on:
      - "sql"
  sql:
    container_name: sql_server
    build: ./Db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=HelloWorldPassword951!